// Copies ABIs out of the hardhat artifacts into src/abi/*.ts so the frontend
// cannot drift from the deployed contracts. Run `npm run abi` after any
// contract change.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const artifacts = resolve(here, "../../contracts/artifacts/contracts");
const outDir = resolve(here, "../src/abi");

const TARGETS = [
  ["TestUSD.sol/TestUSD.json", "testUsd"],
  ["ConfidentialUSD.sol/ConfidentialUSD.json", "confidentialUsd"],
  ["ConfidentialPrizePool.sol/ConfidentialPrizePool.json", "prizePool"],
];

if (!existsSync(artifacts)) {
  console.error(
    `No artifacts at ${artifacts}\nRun \`npm run compile\` in ../contracts first.`
  );
  process.exit(1);
}

mkdirSync(outDir, { recursive: true });

for (const [rel, name] of TARGETS) {
  const path = resolve(artifacts, rel);
  if (!existsSync(path)) {
    console.error(`Missing artifact: ${path}`);
    process.exit(1);
  }
  const { abi } = JSON.parse(readFileSync(path, "utf8"));
  const banner =
    "// GENERATED by scripts/extract-abi.mjs — do not edit.\n" +
    "// Regenerate with `npm run abi` after changing the contracts.\n\n";
  writeFileSync(
    resolve(outDir, `${name}.ts`),
    `${banner}export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`
  );
  console.log(`wrote src/abi/${name}.ts (${abi.length} entries)`);
}
