// GENERATED by scripts/extract-abi.mjs — do not edit.
// Regenerate with `npm run abi` after changing the contracts.

export const yieldSourceAbi = [
  {
    "inputs": [],
    "name": "accrued",
    "outputs": [
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint64",
        "name": "amount",
        "type": "uint64"
      }
    ],
    "name": "harvest",
    "outputs": [
      {
        "internalType": "euint64",
        "name": "moved",
        "type": "bytes32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;
