import { useMemo } from "react";

/// A guilloche rosette — the interlaced line-work engraved on banknotes and
/// share certificates.
///
/// On a banknote the pattern is the anti-forgery device: it is generated by
/// machine from parameters you cannot recover by looking at it. Here it plays
/// the same role literally — every rosette is derived from a real on-chain
/// value, so the ornament IS the ciphertext or the round's entropy, not a
/// picture of one.
///
/// The curve is a superposition of two rotating radii (a hypotrochoid), which
/// is precisely how a rose engine lathe cuts them:
///
///   r(t) = R + a·cos(f·t + φ)
///   x    = r·cos(t),  y = r·sin(t)
///
/// Overlaying several passes at slightly advanced phase gives the woven moiré
/// that makes the pattern read as engraved rather than drawn.
function seedFrom(input: string | bigint | undefined): number {
  if (input === undefined) return 0x9e3779b9;
  const s = typeof input === "bigint" ? input.toString(16) : input;
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h >>> 0;
}

function mulberry(seed: number) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function Guilloche({
  seed,
  size = 120,
  passes = 5,
  className = "",
  stroke = "currentColor",
  opacity = 0.9,
}: {
  seed?: string | bigint;
  size?: number;
  passes?: number;
  className?: string;
  stroke?: string;
  opacity?: number;
}) {
  const paths = useMemo(() => {
    const rnd = mulberry(seedFrom(seed));
    // Petal count and amplitude come from the seed, so two different values
    // never produce the same rosette.
    const freq = 5 + Math.floor(rnd() * 12);
    const amp = 0.16 + rnd() * 0.2;
    const inner = 0.5 + rnd() * 0.22;
    const skew = 1 + rnd() * 0.35;

    const cx = size / 2;
    const cy = size / 2;
    const base = (size / 2) * 0.86;
    const steps = 340;

    const out: string[] = [];
    for (let p = 0; p < passes; p++) {
      const phase = (p / passes) * Math.PI * 0.6;
      const scale = 1 - p * (1 - inner) * (1 / passes);
      let d = "";
      for (let i = 0; i <= steps; i++) {
        const t = (i / steps) * Math.PI * 2;
        const r = base * scale * (1 + amp * Math.cos(freq * t + phase));
        const x = cx + r * Math.cos(t) * skew * 0.98;
        const y = cy + r * Math.sin(t);
        d += `${i === 0 ? "M" : "L"}${x.toFixed(2)},${y.toFixed(2)}`;
      }
      out.push(d + "Z");
    }
    return out;
  }, [seed, size, passes]);

  return (
    <svg
      width={size}
      height={size}
      viewBox={`0 0 ${size} ${size}`}
      className={className}
      aria-hidden="true"
      role="presentation"
    >
      <g fill="none" stroke={stroke} strokeWidth={0.5} opacity={opacity}>
        {paths.map((d, i) => (
          <path key={i} d={d} />
        ))}
      </g>
    </svg>
  );
}

/// A horizontal band of guilloche — the strip that runs across a certificate.
/// Used where a value is sealed: intricate, precise, and unreadable, which is
/// exactly the state of the data underneath it.
export function GuillocheBand({
  seed,
  width = 180,
  height = 26,
  className = "",
  stroke = "currentColor",
}: {
  seed?: string | bigint;
  width?: number;
  height?: number;
  className?: string;
  stroke?: string;
}) {
  const paths = useMemo(() => {
    const rnd = mulberry(seedFrom(seed));
    const waves = 3 + Math.floor(rnd() * 3);
    const freq = 6 + rnd() * 10;
    const out: string[] = [];
    for (let w = 0; w < waves; w++) {
      const phase = rnd() * Math.PI * 2;
      const amp = (height / 2) * (0.45 + rnd() * 0.4);
      let d = "";
      const steps = 200;
      for (let i = 0; i <= steps; i++) {
        const x = (i / steps) * width;
        const u = (i / steps) * Math.PI * 2;
        const y =
          height / 2 +
          amp * Math.sin(freq * u + phase) * Math.cos(u * 1.5 + phase * 0.5);
        d += `${i === 0 ? "M" : "L"}${x.toFixed(2)},${y.toFixed(2)}`;
      }
      out.push(d);
    }
    return out;
  }, [seed, width, height]);

  return (
    <svg
      width={width}
      height={height}
      viewBox={`0 0 ${width} ${height}`}
      className={className}
      aria-hidden="true"
      role="presentation"
    >
      <g fill="none" stroke={stroke} strokeWidth={0.45} opacity={0.85}>
        {paths.map((d, i) => (
          <path key={i} d={d} />
        ))}
      </g>
    </svg>
  );
}
